#!/usr/bin/env bash
# finding out what’s keeping your Ubuntu container’s 
# Nginx installation from listening on port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
