#!/usr/bin/env bash
# finding out what’s keeping your Ubuntu container’s 
# Nginx installation from listening on port 80


apt-get update -y
apt-get install -y nginx
sudo service nginx enable
sudo service nginx start
