#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 20 and:
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

# Initializes the counter
count=1

# Starts the loop

while [ "$count" -le 20 ]; do
    case "$count" in
        4)
            echo "$count: Bad luck from China"
            ;;
        9)
            echo "$count: Bad luck from Japan"
            ;;
        17)
            echo "$count: Bad luck from Italy"
            ;;
        *)
            echo "$count"
            ;;
    esac

    # Increment the counter
    count=$((count + 1))
done
