#!/usr/bin/env bash
#connecting to server using ssh

# Define the server address
SERVER_ADDRESS="100.25.10.7"

# Use the private key ~/.ssh/school to connect as the user ubuntu
ssh -i ~/.ssh/school ubuntu@$SERVER_ADDRESS
